version: 2
jobs:
    build:
        working_directory: /cadquery-models
        docker:
            - image: justbuchanan/docker-cadquery
        steps:
            - run: mkdir /tmp/artifacts

            - checkout

            # Render model
            - run: python2 render.py --file car.py --out_dir /tmp/artifacts

            - store_artifacts:
                path: /tmp/artifacts
            - save_cache:
                key: artifacts-{{ .Branch }}-{{ .Revision }}
                paths:
                    - "/tmp/artifacts"

    deploy_ghpages:
        docker:
            - image: justbuchanan/docker-cadquery
        steps:
            # Add SSH key that allows *pushing* to the github repo.
            # https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-user-key
            - add_ssh_keys:
                fingerprints:
                    - "86:03:e5:b9:32:d8:10:f3:17:0a:80:d8:62:b1:68:ec"

            # setup git
            - run: git config --global user.email "ci@circle"
            - run: git config --global user.name "Circle Ci"

            - restore_cache:
                keys:
                    - artifacts-{{ .Branch }}-{{ .Revision }}

            - checkout
            - run: git checkout gh-pages
            - run: git status
            - run: ls -l

            # clear previous output
            - run: rm -rf ./*

            # copy build outputs to 'model' directory
            - run: mkdir model
            - run: cp -r /tmp/artifacts/* ./model

            # copy static resources from cqparts
            - run: cp -r /examples/cqparts/src/cqparts/display/web-template/* ./

            # fix urls: /static/ -> /$reponame/static/
            - run: sed -i 's/\/static\//\/cadquery-models\/static\//g' index.html

            # fix model path
            - run: sed -i 's/out\.gltf/Car\/Car\.gltf/g' static/js/cqpartsViewer.js

            # deploy gh-pages branch
            - run: git add .
            - run: git commit -m 'update pages'
            - run: git push origin gh-pages


workflows:
    version: 2
    all:
        jobs:
            - build
            - deploy_ghpages:
                requires:
                    - build
